- name: feature
  color: "0E8A16"
  description: "Neue Funktionalität"
- name: bug
  color: "D73A4A"
  description: "Fehler"
- name: triage
  color: "FBCA04"
  description: "Sichtung/Einordnung nötig"
- name: docs
  color: "0075ca"
  description: "Dokumentationsänderungen"
- name: refactor
  color: "C5DEF5"
  description: "Code-Umstrukturierung"
