name: "Bug report"
description: "Fehler melden"
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: input
    id: summary
    attributes:
      label: Kurzbeschreibung
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Schritte zur Reproduktion
      placeholder: "1) ... 2) ... 3) ..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Erwartetes Verhalten
  - type: textarea
    id: actual
    attributes:
      label: Tatsächliches Verhalten / Logs
  - type: input
    id: env
    attributes:
      label: Umgebung
      placeholder: "OS/Plattform, App-Version, Device, .NET SDK"
