name: Enforce Linked Issue
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  enforce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body || "";
            const title = context.payload.pull_request.title || "";
            const pattern = /(close[sd]?|fix(e[sd])?|resolve[sd]?)\s+#\d+/i;
            if (!pattern.test(body) && !pattern.test(title)) {
              core.setFailed("PR muss ein Issue verknüpfen (z. B. 'Closes #123').");
            }
